package com.mazes.model.dungeon.allocator;

public interface TerrainTilesIds {

    int NO_TILE=-1;
    int WALL_SOLID=1;
    int FLOOR=0;
    int SIDE_RIGHT=11;
    int SIDE_LEFT=12;
    int WALL_FRONT_BOTTOM=13;
    int WALL_FRONT_TOP=15;
    int SIDE_BOTTOM=14;
    int WALL_TOP_WALL_SIDE_LEFT=16;
    int WALL_TOP_WALL_SIDE_RIGHT=17;
    int WALL_TOP_SIDE_RIGHT=10;
    int WALL_TOP_SIDE_LEFT=20;
    int WALL_SIDE_LEFT=18;
    int WALL_SIDE_RIGHT=19;
    int SIDE_CONNECTOR_TOP_TO_LEFT=21;
    int SIDE_CONNECTOR_TOP_TO_RIGHT=22;
    int SIDE_CONNECTOR_BOTTOM_TO_RIGHT=23;
    int SIDE_CONNECTOR_BOTTOM_TO_LEFT=24;
    int WALL_CONNECTOR_BOTTOM_TO_LEFT=25;
    int WALL_CONNECTOR_BOTTOM_TO_RIGHT=26;
    int SIDE_LEFT_WITH_WALL_CONNECTOR=27;
    int SIDE_RIGHT_WITH_WALL_CONNECTOR=28;
    int SIDE_CONNECTOR_TR_WITH_WALL_CONN=29;
    int SIDE_CONNECTOR_TL_WITH_WALL_CONN=30;
    int WALL_CORNER_TOP_RIGHT=31;
    int WALL_CORNER_TOP_LEFT=32;
    int CORNER_BR=33;
    int CORNER_BL=34;
    int SIDE_CONNECTOR_TL_WITH_WALL_SIDE_RIGHT=35;
    int SIDE_CONNECTOR_TR_WITH_WALL_SIDE_LEFT=36;

    int SHADOW_BOTTOM_WALL_CORNER = 41;
    int SHADOW_INNER_CORNER = 42;
    int SHADOW_OUTER_CORNER = 43;
    int SHADOW_LEFT_SIDE = 44;
    int SHADOW_SIDE_BOTTOM = 45;
    int SHADOW_TOP_SIDE_CORNER = 46;

}
